// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourGuideApp.Data;

#nullable disable

namespace TourGuideApp.Migrations
{
    [DbContext(typeof(TourGuideContext))]
    [Migration("20260628183713_AddIsActiveToUser")]
    partial class AddIsActiveToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TourGuideApp.Models.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("ListenCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("POIId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranscriptText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("POIId");

                    b.ToTable("Audios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AudioUrl = "/audio/poi1_vi.mp3",
                            LanguageCode = "vi",
                            ListenCount = 0,
                            POIId = 1,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 2,
                            AudioUrl = "/audio/poi1_en.mp3",
                            LanguageCode = "en",
                            ListenCount = 0,
                            POIId = 1,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 3,
                            AudioUrl = "/audio/poi2_vi.mp3",
                            LanguageCode = "vi",
                            ListenCount = 0,
                            POIId = 2,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 4,
                            AudioUrl = "/audio/poi2_en.mp3",
                            LanguageCode = "en",
                            ListenCount = 0,
                            POIId = 2,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 5,
                            AudioUrl = "/audio/poi2_ko.mp3",
                            LanguageCode = "ko",
                            ListenCount = 0,
                            POIId = 2,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 6,
                            AudioUrl = "/audio/poi2_zh.mp3",
                            LanguageCode = "zh",
                            ListenCount = 0,
                            POIId = 2,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 7,
                            AudioUrl = "/audio/poi3_vi.mp3",
                            LanguageCode = "vi",
                            ListenCount = 0,
                            POIId = 3,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 8,
                            AudioUrl = "/audio/poi3_zh.mp3",
                            LanguageCode = "zh",
                            ListenCount = 0,
                            POIId = 3,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 9,
                            AudioUrl = "/audio/poi3_en.mp3",
                            LanguageCode = "en",
                            ListenCount = 0,
                            POIId = 3,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 10,
                            AudioUrl = "/audio/poi3_ko.mp3",
                            LanguageCode = "ko",
                            ListenCount = 0,
                            POIId = 3,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 11,
                            AudioUrl = "/audio/poi4_vi.mp3",
                            LanguageCode = "vi",
                            ListenCount = 0,
                            POIId = 4,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 12,
                            AudioUrl = "/audio/poi4_ko.mp3",
                            LanguageCode = "ko",
                            ListenCount = 0,
                            POIId = 4,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 13,
                            AudioUrl = "/audio/poi4_zh.mp3",
                            LanguageCode = "zh",
                            ListenCount = 0,
                            POIId = 4,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 14,
                            AudioUrl = "/audio/poi4_en.mp3",
                            LanguageCode = "en",
                            ListenCount = 0,
                            POIId = 4,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 15,
                            AudioUrl = "/audio/poi5_vi.mp3",
                            LanguageCode = "vi",
                            ListenCount = 0,
                            POIId = 5,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 16,
                            AudioUrl = "/audio/poi5_en.mp3",
                            LanguageCode = "en",
                            ListenCount = 0,
                            POIId = 5,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 17,
                            AudioUrl = "/audio/poi5_ko.mp3",
                            LanguageCode = "ko",
                            ListenCount = 0,
                            POIId = 5,
                            TranscriptText = ""
                        },
                        new
                        {
                            Id = 18,
                            AudioUrl = "/audio/poi5_zh.mp3",
                            LanguageCode = "zh",
                            ListenCount = 0,
                            POIId = 5,
                            TranscriptText = ""
                        });
                });

            modelBuilder.Entity("TourGuideApp.Models.ListenHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ListenedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("POIId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("POIId");

                    b.ToTable("ListenHistories");
                });

            modelBuilder.Entity("TourGuideApp.Models.POI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VendorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VendorId");

                    b.ToTable("POIs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Điểm khởi đầu tuyến phố ẩm thực Vĩnh Khánh, Quận 4.",
                            Lat = 10.76,
                            Lng = 106.696,
                            Name = "Cổng phố ẩm thực Vĩnh Khánh",
                            Priority = 1,
                            Radius = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Quán ốc nổi tiếng lâu đời trên phố Vĩnh Khánh.",
                            Lat = 10.759499999999999,
                            Lng = 106.6965,
                            Name = "Ốc Đào Vĩnh Khánh",
                            Priority = 2,
                            Radius = 80.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Khu vực tập trung các xe bánh tráng trộn về đêm.",
                            Lat = 10.759,
                            Lng = 106.697,
                            Name = "Bánh tráng trộn Vĩnh Khánh",
                            Priority = 3,
                            Radius = 80.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Quán bánh flan nổi tiếng trên phố Vĩnh Khánh.",
                            Lat = 10.76139,
                            Lng = 106.70010000000001,
                            Name = "Bánh Flan Ngọc Nga",
                            Priority = 3,
                            Radius = 80.0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Quán ốc Oanh nổi tiếng trên phố Vĩnh Khánh.",
                            Lat = 10.75902,
                            Lng = 106.69718,
                            Name = "Ốc Oanh Vĩnh Khánh",
                            Priority = 2,
                            Radius = 80.0
                        });
                });

            modelBuilder.Entity("TourGuideApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TourGuideApp.Models.Audio", b =>
                {
                    b.HasOne("TourGuideApp.Models.POI", "POI")
                        .WithMany("Audios")
                        .HasForeignKey("POIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("POI");
                });

            modelBuilder.Entity("TourGuideApp.Models.ListenHistory", b =>
                {
                    b.HasOne("TourGuideApp.Models.POI", "POI")
                        .WithMany()
                        .HasForeignKey("POIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("POI");
                });

            modelBuilder.Entity("TourGuideApp.Models.POI", b =>
                {
                    b.HasOne("TourGuideApp.Models.User", null)
                        .WithMany("OwnedPOIs")
                        .HasForeignKey("UserId");

                    b.HasOne("TourGuideApp.Models.User", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("TourGuideApp.Models.POI", b =>
                {
                    b.Navigation("Audios");
                });

            modelBuilder.Entity("TourGuideApp.Models.User", b =>
                {
                    b.Navigation("OwnedPOIs");
                });
#pragma warning restore 612, 618
        }
    }
}
