// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourGuideApp.Data;

#nullable disable

namespace TourGuideApp.Migrations
{
    [DbContext(typeof(TourGuideContext))]
    [Migration("20260619012858_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TourGuideApp.Models.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("ListenCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("POIId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranscriptText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("POIId");

                    b.ToTable("Audios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AudioUrl = "/audio/poi1_vi.mp3",
                            LanguageCode = "vi",
                            ListenCount = 0,
                            POIId = 1,
                            TranscriptText = "Chào mừng bạn đến với phố ẩm thực Vĩnh Khánh."
                        },
                        new
                        {
                            Id = 2,
                            AudioUrl = "/audio/poi1_en.mp3",
                            LanguageCode = "en",
                            ListenCount = 0,
                            POIId = 1,
                            TranscriptText = "Welcome to Vinh Khanh food street."
                        },
                        new
                        {
                            Id = 3,
                            AudioUrl = "/audio/poi2_vi.mp3",
                            LanguageCode = "vi",
                            ListenCount = 0,
                            POIId = 2,
                            TranscriptText = "Đây là quán ốc nổi tiếng, hoạt động từ năm 1990."
                        },
                        new
                        {
                            Id = 4,
                            AudioUrl = "/audio/poi2_en.mp3",
                            LanguageCode = "en",
                            ListenCount = 0,
                            POIId = 2,
                            TranscriptText = "This is a famous snail restaurant, operating since 1990."
                        });
                });

            modelBuilder.Entity("TourGuideApp.Models.ListenHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ListenedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("POIId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("POIId");

                    b.ToTable("ListenHistories");
                });

            modelBuilder.Entity("TourGuideApp.Models.POI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("POIs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Điểm khởi đầu tuyến phố ẩm thực Vĩnh Khánh, Quận 4.",
                            Lat = 10.76,
                            Lng = 106.696,
                            Name = "Cổng phố ẩm thực Vĩnh Khánh",
                            Priority = 1,
                            Radius = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Quán ốc nổi tiếng lâu đời trên phố Vĩnh Khánh.",
                            Lat = 10.759499999999999,
                            Lng = 106.6965,
                            Name = "Ốc Đào Vĩnh Khánh",
                            Priority = 2,
                            Radius = 80.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Khu vực tập trung các xe bánh tráng trộn về đêm.",
                            Lat = 10.759,
                            Lng = 106.697,
                            Name = "Bánh tráng trộn Vĩnh Khánh",
                            Priority = 1,
                            Radius = 80.0
                        });
                });

            modelBuilder.Entity("TourGuideApp.Models.Audio", b =>
                {
                    b.HasOne("TourGuideApp.Models.POI", "POI")
                        .WithMany("Audios")
                        .HasForeignKey("POIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("POI");
                });

            modelBuilder.Entity("TourGuideApp.Models.ListenHistory", b =>
                {
                    b.HasOne("TourGuideApp.Models.POI", "POI")
                        .WithMany()
                        .HasForeignKey("POIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("POI");
                });

            modelBuilder.Entity("TourGuideApp.Models.POI", b =>
                {
                    b.Navigation("Audios");
                });
#pragma warning restore 612, 618
        }
    }
}
